[package]
name = "misc_objects"
version = "0.1.0"
authors = ["TheZoq2 <frans.skarman@gmail.com>"]
edition = "2018"

[dependencies]
scad = "1.0.3"
scad_util = {git = "https://github.com/TheZoq2/Rust-scad-util.git"}
nalgebra = "*"
